name: Docker build
on:
  push:
    branches: ['main']
  pull_request:
  schedule:
    - cron: '0 11 * * *'
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build spaceros image
        uses: docker/build-push-action@v2
        with:
          context: spaceros
          push: false
          tags: |
            spaceros
            ebenevedes/spaceros:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: true

  build-and-test-ws:
    needs: build-image
    runs-on: ubuntu-latest
    container:
      image: ebenevedes/spaceros:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Build workspace
        run: colcon build

      - name: Test workspace
        run: colcon test
